name: aanaxagorasr_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.0.9
  get_it: ^7.2.0
  carousel_pro: ^1.0.0
  icon_picker: "^1.1.0"
  share: ^2.0.4
  filter_list: ^1.0.0
  carousel_slider: ^4.0.0


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - android/assests/images/photo1.png
    - android/assests/images/photo2.png
    - android/assests/images/photo3.jpeg
    - android/assests/images/photo4.jpg
    - android/assests/images/photo5.jpg
    - android/assests/images/photo6.jpg
    - android/assests/images/logo2.png
    - android/assests/images/logo1.png
    - android/assests/images/webdesign1.png
    - android/assests/images/webdesign2.png
    - android/assests/images/gif.png
    - android/assests/images/design2.png
    - android/assests/images/logobanner.png
    - android/assests/images/graphicsdesign1.png
    - android/assests/images/webdevelopmentbanner1.png
    - android/assests/images/webdevelopmentbanner2.png
    - android/assests/images/ecommerce.jpg
    - android/assests/images/ecommerce2.png
    - android/assests/images/appdevelopment1.jpg
    - android/assests/images/appdevelopment2.png
    - android/assests/images/softwaredevelopment1.jpg
    - android/assests/images/softwaredevelopment2.png
    - android/assests/images/PPC1.jpg
    - android/assests/images/PPC2.png
    - android/assests/images/SEO1.png
    - android/assests/images/SEO2.png
    - android/assests/images/SMO1.jpg
    - android/assests/images/SMO2.png
    - android/assests/images/profile.jpg
    - android/assests/images/php1.png
    - android/assests/images/php2.png
    - android/assests/images/Portfolio1.png
    - android/assests/images/Portfolio2.png
    - android/assests/images/Portfolio3.png
    - android/assests/images/Portfolio4.png
    - android/assests/images/Portfolio5.png
    - android/assests/images/Portfolio6.png
    - android/assests/images/Portfolio7.png
    - android/assests/images/Portfolio8.png
    - android/assests/images/Portfolio9.png
    - android/assests/images/Portfolio10.png
    - android/assests/images/Portfolio11.png
    - android/assests/images/Portfolio12.png
    - android/assests/images/Portfolio13.png
    - android/assests/images/yogisena.png
    - android/assests/images/indolite.png
    - android/assests/images/mysutraa.png
    - android/assests/images/bckg.jpg
    - android/assests/images/AbhinavSir.png
    - android/assests/images/sign.png
    - android/assests/images/ProfessionalMan.png
    - android/assests/images/globe.png
    - android/assests/images/webapp1.gif
    - android/assests/images/webApp2.png
    - android/assests/images/mobileApp1.gif
    - android/assests/images/MobileApp2.png
    - android/assests/images/Ecommerce1.png
    - android/assests/images/DigitalMarketing1.gif
    - android/assests/images/Digital1.png
    - android/assests/images/cloud-1.png
    - android/assests/images/MachineAI.png
    - android/assests/images/MachineAI1.gif
    - android/assests/images/facebook.png
    - android/assests/images/link.png
    - android/assests/images/insta.png
    - android/assests/images/Bag.png
    - android/assests/images/Smile.png
    - android/assests/images/Handshake.png
    - android/assests/images/briefcase.png
    - android/assests/images/Google.png
    - android/assests/images/blog.png
    - android/assests/images/Gif.gif
    - android/assests/images/blog-page.png
    - android/assests/images/blog1.jpg
    - android/assests/images/blog2.png
    - android/assests/images/Drawerimage.jpg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
